import { Mainlayout } from "@/component/layouts/Mainlayout";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/css/bootstrap.rtl.min.css";
import type { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { Lexend } from "next/font/google";
import "./globals.scss";
import Script from "next/script";

const inter = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "e-Procure Finance",
  description: "Generated by e-Procure Finance",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <head>
      <Script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js" />
       
      </head>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Mainlayout locale={locale}>{children}</Mainlayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
